import { Task } from './types';

export const mockKanbanTasks: Task[] = [
    {
        id: '1',
        title: 'Document Audit and Review',
        subtitle: 'Energy Charter Treaty',
        priority: 'high',
        status: 'backlog',
        dueDate: '2024-11-04',
        attachmentsCount: 2,
        commentsCount: 5,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=John+Doe&background=FF6B6B&color=fff',
    },
    {
        id: '2',
        title: 'Compliance Policy Update',
        subtitle: 'Human Rights',
        priority: 'medium',
        status: 'backlog',
        dueDate: '2024-11-10',
        attachmentsCount: 1,
        commentsCount: 2,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Jane+Smith&background=4ECDC4&color=fff',
    },
    {
        id: '3',
        title: 'Risk Assessment Survey',
        subtitle: 'Emission Savings Feature',
        priority: 'urgent',
        status: 'todo',
        dueDate: '2024-11-02',
        attachmentsCount: 0,
        commentsCount: 2,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Mike+Johnson&background=95E1D3&color=333',
    },
    {
        id: '4',
        title: 'Employee Training Certification',
        subtitle: 'Supply chain transparency',
        priority: 'medium',
        status: 'todo',
        dueDate: '2024-11-07',
        attachmentsCount: 3,
        commentsCount: 1,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Sarah+Williams&background=F38181&color=fff',
    },
    {
        id: '5',
        title: 'Incident Reporting',
        subtitle: 'Immediate Disclosure Rule',
        priority: 'low',
        status: 'todo',
        dueDate: '2024-11-15',
        attachmentsCount: 0,
        commentsCount: 0,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Tom+Brown&background=78C850&color=fff',
    },
    {
        id: '6',
        title: 'Regulatory Submission Deadline',
        subtitle: 'Impact investments',
        priority: 'urgent',
        status: 'in_progress',
        dueDate: '2024-11-01',
        attachmentsCount: 2,
        commentsCount: 6,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Emily+Davis&background=A29BFE&color=fff',
    },
    {
        id: '7',
        title: 'Third-Party Vendor Due Diligence',
        subtitle: 'Energy Charter Treaty',
        priority: 'medium',
        status: 'in_progress',
        dueDate: '2024-11-07',
        attachmentsCount: 2,
        commentsCount: 2,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Alex+Martinez&background=FD79A8&color=fff',
    },
    {
        id: '8',
        title: 'Data Protection Compliance Check',
        subtitle: 'Supply chain transparency',
        priority: 'high',
        status: 'in_progress',
        dueDate: '2024-11-10',
        attachmentsCount: 3,
        commentsCount: 8,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Chris+Lee&background=FDCB6E&color=333',
    },
    {
        id: '9',
        title: 'Internal Audit Preparation',
        subtitle: 'Human Rights',
        priority: 'low',
        status: 'in_progress',
        dueDate: '2024-11-12',
        attachmentsCount: 3,
        commentsCount: 1,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Pat+Wilson&background=6C5CE7&color=fff',
    },
    {
        id: '10',
        title: 'Internal Audit Preparation',
        subtitle: 'Standards for Reuse and Recycling',
        priority: 'high',
        status: 'for_review',
        dueDate: '2024-11-05',
        attachmentsCount: 2,
        commentsCount: 5,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Jordan+Taylor&background=FF7675&color=fff',
    },
    {
        id: '11',
        title: 'Policy Exception Request',
        subtitle: 'Greenwashing',
        priority: 'medium',
        status: 'for_review',
        dueDate: '2024-11-06',
        attachmentsCount: 0,
        commentsCount: 1,
        assigneeAvatar: 'https://ui-avatars.com/api/?name=Sam+Anderson&background=00B894&color=fff',
    },
];
